import type { Theme } from "./index";

export const ramenTheme: Theme = {
  id: "ramen",
  name: "赤猫拉面馆",
  icon: "🍜",
  colors: {
    bg: "#EDE6D8",
    sidebar: "#E5DDCF",
    card: "#F5F0E8",
    border: "#B8AD9A",
    text: "#1E1810",
    textMuted: "#5C5245",
    primary: "#B8432A",
    primaryHover: "#9E3820",
    accent: "#C78B2E",
    userBubble: "#B8432A",
    userBubbleText: "#FFFBF5",
    assistantBubble: "#F5F0E8",
    assistantBubbleText: "#1E1810",
    inputBg: "#F5F0E8",
    inputBorder: "#B8AD9A",
  },
  headerTitle: "赤猫拉面馆",
  headerSubtitle: "Akaneko · Ramen",
  newThreadLabel: "来一碗",
  agents: {
    sasaki: {
      name: "佐佐木",
      avatar: "/avatars/sasaki.png",
      title: "前厅经理 · 前端开发",
      color: "text-sky-300",
      ring: "ring-sky-700/50",
      border: "border-sky-700/50",
    },
    bunzo: {
      name: "文藏",
      avatar: "/avatars/bunzo.png",
      title: "底汤主厨 · 后端开发",
      color: "text-orange-300",
      ring: "ring-orange-700/50",
      border: "border-orange-700/50",
    },
    kohana: {
      name: "小花",
      avatar: "/avatars/kohana.png",
      title: "品控 · QA 测试",
      color: "text-emerald-300",
      ring: "ring-emerald-700/50",
      border: "border-emerald-700/50",
    },
    sabu: {
      name: "萨布",
      avatar: "/avatars/sabu.png",
      title: "暗巷 · 文档专家",
      color: "text-purple-300",
      ring: "ring-purple-700/50",
      border: "border-purple-700/50",
    },
  },
};
