import type { Theme } from "./index";

export const ramenTheme: Theme = {
  id: "ramen",
  name: "赤猫拉面馆",
  icon: "🍜",
  colors: {
    bg: "#3E2E22",
    sidebar: "#2E2018",
    card: "#4E3A2C",
    border: "#7A6450",
    text: "#FFF8E7",
    textMuted: "#BFA080",
    primary: "#D4603E",
    primaryHover: "#C84B31",
    accent: "#F0A500",
    userBubble: "#FFF8EE",
    userBubbleText: "#4E3A2C",
    assistantBubble: "#4E3A2C",
    assistantBubbleText: "#FFF8E7",
    inputBg: "#4E3A2C",
    inputBorder: "#7A6450",
  },
  headerTitle: "赤猫拉面馆",
  headerSubtitle: "Ramen Akaneko",
  newThreadLabel: "来一碗",
  agents: {
    sasaki: {
      name: "佐佐木",
      avatar: "/avatars/sasaki.png",
      title: "前厅经理 · 前端开发",
      color: "text-sky-300",
      ring: "ring-sky-700/50",
      border: "border-sky-700/50",
    },
    bunzo: {
      name: "文藏",
      avatar: "/avatars/bunzo.png",
      title: "底汤主厨 · 后端开发",
      color: "text-orange-300",
      ring: "ring-orange-700/50",
      border: "border-orange-700/50",
    },
    kohana: {
      name: "小花",
      avatar: "/avatars/kohana.png",
      title: "品控 · QA 测试",
      color: "text-emerald-300",
      ring: "ring-emerald-700/50",
      border: "border-emerald-700/50",
    },
  },
};
